app = 'Cabañas_Mexiquillo'
primary_region = 'gdl'
console_command = '/backend/manage.py shell'

[build]
  dockerfile = "./backend/Dockerfile"
  args = { PORT = "8000" }

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[deploy]
  memory = 1024
  cpus = 1

[[statics]]
  guest_path = '/backend/static'
  url_prefix = '/static/'
