# Generated by Django 5.1.1 on 2024-09-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('costo_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendador')),
            ],
        ),
    ]
