# Generated by Django 4.2.9 on 2024-11-20 14:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_alter_persona_dni'),
        ('cabanas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicacabana',
            name='cabana',
        ),
        migrations.AlterModelOptions(
            name='cabana',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imagencabana',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='acepta_mascotas',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='calificacion_promedio',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='costo_limpieza',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='deposito_garantia',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='es_destacada',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='metros_cuadrados',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='num_banos',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='num_habitaciones',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='num_resenas',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='tiempo_maximo_estadia',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='tiempo_minimo_estadia',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='tiene_alberca',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='tiene_jacuzzi',
        ),
        migrations.RemoveField(
            model_name='cabana',
            name='veces_reservada',
        ),
        migrations.RemoveField(
            model_name='imagencabana',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='imagencabana',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='imagencabana',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cabana',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabanas', to='usuarios.arrendador'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='capacidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='cabanas.servicio'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabanas', to='cabanas.ubicacion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('cabana', 'usuario')},
        ),
        migrations.DeleteModel(
            name='DisponibilidadCabana',
        ),
        migrations.DeleteModel(
            name='PoliticaCabana',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='actualizada_en',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='fecha_estadia',
        ),
    ]
