# fly.toml app configuration file generated for axolpos-backend on 2024-10-27T01:18:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axolpos-backend'
primary_region = 'gdl'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  DJANGO_ALLOWED_HOSTS = 'axolpos-backend.fly.dev'
  DJANGO_CORS_ALLOWED_ORIGINS = 'https://axolpos-frontend.fly.dev'
  DJANGO_SETTINGS_MODULE = 'myproject.settings.production'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/health/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static'

